### ISSUE TITLE
缺少规则（应该是）

### ISSUE THREAD

**Issue by flamingocc** [vacabun/weibo-dl#2]
微博搜索后，地址变更为：s.weibo.com/* ，导致插件识别不到
![image](https://github.com/vacabun/weibo-dl/assets/35923915/2ce230c4-d797-44f0-ac93-d459c7654c1e)
![image](https://github.com/vacabun/weibo-dl/assets/35923915/faccdef7-04b3-4c84-bc68-418bed93bd5f)

目前自带两个规则为：
https://weibo.com/*
https://www.weibo.com/*

**Comment by flamingocc** [comment]
另外，能支持m.weibo.cn的话更好了，一些发布者会发布这样地址的内容。
https://m.weibo.cn/detail/5013831581958964?sudaref=dig.chouti.com&display=0&retcode=6102
![image](https://github.com/vacabun/weibo-dl/assets/35923915/3ba22cff-7621-4692-b664-efc5952891f6)

感谢！🙏

**Comment by vacabun** [comment]
目前还没适配这两个页面，可以复制复制链接重新打开就能进到普通的页面了。
<img width="933" alt="image" src="https://github.com/vacabun/weibo-dl/assets/34151213/753bcdef-650f-41e6-865e-4ad4998291d2">
<img width="987" alt="image" src="https://github.com/vacabun/weibo-dl/assets/34151213/8570945e-8042-4b40-a71a-567acecb3db1">
<img width="990" alt="image" src="https://github.com/vacabun/weibo-dl/assets/34151213/fa0a2231-d6a0-4ac5-b2ef-5544c76a3494">

**Comment by flamingocc** [comment]
> 目前还没适配这两个页面，复制链接重新打开就能进到普通的页面了。 <img alt="image" width="933" src="https://private-user-images.githubusercontent.com/34151213/314442798-753bcdef-650f-41e6-865e-4ad4998291d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzM1MjksIm5iZiI6MTcxMDkzMzIyOSwicGF0aCI6Ii8zNDE1MTIxMy8zMTQ0NDI3OTgtNzUzYmNkZWYtNjUwZi00MWU2LTg2NWUtNGFkNDk5ODI5MWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExMTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZTg1YTE4MWYwMjJhNzhjZjQxMDUyOWQ4NTg5YThmOGIzNTYxYzNlMzUzOTNhZWZjYjEzNWZmODgxMGIxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZDn5ayUp2zvf7pFshWxXAGRXTF2msr1s4v4l50UK5Sk"> <img alt="image" width="987" src="https://private-user-images.githubusercontent.com/34151213/314442857-8570945e-8042-4b40-a71a-567acecb3db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzM1MjksIm5iZiI6MTcxMDkzMzIyOSwicGF0aCI6Ii8zNDE1MTIxMy8zMTQ0NDI4NTctODU3MDk0NWUtODA0Mi00YjQwLWE3MWEtNTY3YWNlY2IzZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExMTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTM5MTk5OTJkY2M4NDM3MzQzMDQ0Mjc1NmUzNGNlNzllMDk4NTIzZWQ2NjYzM2Q5ZTA4YWUxNDNhN2EwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zQ5sTjeAVUtOqhzsvTu2Bl07eNQiG6mrLrhHww0jBrg"> <img alt="image" width="990" src="https://private-user-images.githubusercontent.com/34151213/314443222-fa0a2231-d6a0-4ac5-b2ef-5544c76a3494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzM1MjksIm5iZiI6MTcxMDkzMzIyOSwicGF0aCI6Ii8zNDE1MTIxMy8zMTQ0NDMyMjItZmEwYTIyMzEtZDZhMC00YWM1LWIyZWYtNTU0NGM3NmEzNDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExMTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ODcyMjQ4YzIxMjFiNTQwMjYzNjc0ZjZmOTlmMTlhYmRiMTgxNDVmNDNhZDIzZTZkYTQ2OWE5NjQzMjQyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3gVqQvLYs1FUjEoRUVinsuJKjS64ZZez6-Fq-toUXU4">

好的，感谢！
